Add tooltip name of tech stack on hover #3
mittal-parth/personal-portfolio pull request #33
Opened 2022-10-04 06:16 UTC by AhmdFarzki

Hi @mittal-parth, I have fixed this problem. Please check and merge if appropriate. Thank you.

![Screenshot (86)](https://user-images.githubusercontent.com/54702541/193747815-80c8f8a8-7158-4956-b0f9-1ba1556a93fd.png)

2022-10-05 09:27 UTC, mittal-parth requested changes
Thanks for making the PR!
- [ ] Please checkout the `package-lock.json` file from the PR.
- [ ] Is it possible to add like an upward arrow to the tooltip, so it looks more like a tooltip?

2022-10-05 09:27 UTC, mittal-parth commented on src/index.css
> +  font-size: 18px;
I'd prefer a smaller text size
```suggestion
  font-size: 14px;
```

2022-10-05 09:27 UTC, mittal-parth commented on src/constants/index.js
> +        name: "Google"
```suggestion
        name: "Google OAuth"
```

2022-10-05 09:27 UTC, mittal-parth commented on src/components/Projects.jsx
> +                  too
`too` Is this required?

2022-10-05 09:38 UTC, AhmdFarzki commented on src/components/Projects.jsx
> +                  too
No, I'm sorry it's my fault

2022-10-05 09:45 UTC, AhmdFarzki commented
Sorry i dont understand about "Please checkout the package-lock.json file from the PR." can your explaint this?

2022-10-05 10:51 UTC, mittal-parth commented
> Sorry i dont understand about "Please checkout the package-lock.json file from the PR." can your explaint this?

Never mind. Coming from Ruby on Rails background, I thought it shouldn't be commited like Gemfile-lock. You can ignore that.

2022-10-06 01:29 UTC, AhmdFarzki commented
Hi @mittal-parth, I have added arrows in the tooltip, please check again.

2022-10-06 01:35 UTC, AhmdFarzki reviewed
I've added upward arrow in the tooltip

2022-10-06 02:42 UTC, mittal-parth approved these changes
Looks great!

2022-10-06 02:43 UTC, merged

2022-10-06 02:44 UTC, mittal-parth commented
@AhmdFarzki Merged!
Thanks for contributing. Do give it a star if you feel like it! 💙